name=7Semi_LPS28DFW
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=Arduino library for the LPS28DFW pressure sensor.
paragraph=This library provides an easy interface for the ST LPS28DFW pressure sensor. It supports pressure (hPa) and temperature (°C) measurement, configurable output data rate, averaging, FIFO, interrupts, and offset calibration.
category=Sensors
url=https://github.com/7semi-solutions/7Semi-LPS28DFW
architectures=*
includes=7Semi_LPS28DFW.h
